sudo: required
language: python
python:
  - "3.6"

script:
  - pip3 install -r requirements.txt
  - python3 fccid.py
  - python3 tenaa_cert.py
  - python3 tenaa_mobile.py
  - python3 nbtc.py
  - python3 tkdn.py
  - python3 wifi.py
  - python3 mi_global.py
  - python3 mi_india.py
  - python3 aio.py

notifications:
  email:
    on_success: never
    on_failure: always
