sudo: required
language: python
python:
  - "3.6"

script:
  - pip3 install -r requirements.txt
  - python3 tenaa.py
  - python3 wifi.py
  - python3 mi_global.py
  - python3 mi_india.py
  - python3 nbtc.py

notifications:
  email:
    on_success: never
    on_failure: always
